#include "FlashReaderFont.h"

#include <Logging.h>

#include <cstring>

// Generated by lib/EpdFont/scripts/fontconvert.py from the Amazon Ember +
// IBM Plex Sans TC stack, uncompressed 2-bit, at FLASH_FONT_POINT_SIZE:
//
//   fontconvert.py --2bit <top-1000 CJK intervals> \
//       emberplex_14_regular 14 AmazonEmber_Rg.ttf IBMPlexSansTC-Regular+rescue.ttf
//
// Uncompressed on purpose: a compressed font needs a DRAM decompression buffer,
// which would defeat the point. Uncompressed bitmaps are read straight out of
// memory-mapped flash.
#include "builtinFonts/emberplex_14_bold.h"
#include "builtinFonts/emberplex_14_regular.h"

namespace {

constexpr uint8_t FLASH_FONT_POINT_SIZE = 14;

// Regular carries the top 1500 CJK characters, bold the top 500.
//
// The asymmetry is measured, not arbitrary. Across a 10-book library, bold is
// 0.92% of all text — but its distribution is wildly uneven: 0.09% in 迷霧之子
// 首部曲 against 29.6% in 讓愛延續的七個方法, whose publisher sets font-weight:bold
// on its 楷體 class. Bold also draws on a much smaller vocabulary (~1500 distinct
// CJK across the library, against ~2000 for regular in a single novel), so 500
// glyphs already covers 88.5% of bold CJK where 1500 regular covers ~97.9%.
//
// Style ids follow EpdFontFamily: 0 regular, 1 bold, 2 italic, 3 bold-italic.
// Italic has no flash backing — Ember's italics are a separate face and italic
// is rarer than bold in these books — so it falls through to the SD font.
const EpdFontData* flashDataFor(const uint8_t style) {
  switch (style) {
    case 0:
      return &emberplex_14_regular;
    case 1:
      return &emberplex_14_bold;
    default:
      return nullptr;
  }
}

// Mutable copies of the flash EpdFontData. The arrays they point at stay in
// flash; only these ~80-byte headers live in RAM, because the generated data is
// `static const` and the glyph-miss hooks have to be written somewhere.
struct Binding {
  EpdFontData data{};
  EpdFont font{nullptr};
  bool bound = false;
};

Binding& bindingFor(const uint8_t style) {
  static Binding bindings[SdCardFont::MAX_STYLES];
  return bindings[style];
}

}  // namespace

uint8_t FlashReaderFont::pointSize() { return FLASH_FONT_POINT_SIZE; }

bool FlashReaderFont::hasStyle(const uint8_t style) {
  return style < SdCardFont::MAX_STYLES && flashDataFor(style) != nullptr;
}

EpdFont* FlashReaderFont::bind(SdCardFont& sdFont, const uint8_t style) {
  if (!hasStyle(style)) return nullptr;

  Binding& b = bindingFor(style);
  b.data = *flashDataFor(style);  // copies the header; arrays stay in flash
  if (!sdFont.attachAsGlyphTail(b.data, style)) {
    LOG_ERR("FLFONT", "SD font has no style %u to serve as tail", style);
    return nullptr;
  }
  b.font.data = &b.data;
  b.bound = true;
  LOG_DBG("FLFONT", "style %u: %u flash glyphs in %u intervals, SD serves the tail", style,
          static_cast<unsigned>(b.data.intervalCount), static_cast<unsigned>(b.data.intervalCount));
  return &b.font;
}

void FlashReaderFont::reset() {
  for (uint8_t i = 0; i < SdCardFont::MAX_STYLES; i++) {
    Binding& b = bindingFor(i);
    b.data = EpdFontData{};
    b.font.data = nullptr;
    b.bound = false;
  }
}
